"""Initial migration

Revision ID: 0bda07422d1f
Revises: 
Create Date: 2025-04-08 21:25:37.509471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bda07422d1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actuators',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('additionalInfo', sa.JSON(), nullable=True),
    sa.Column('flow_rate', sa.Float(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('power_consumption', sa.Float(), nullable=True),
    sa.Column('monitoring_active', sa.Boolean(), nullable=True),
    sa.Column('last_state_change', sa.DateTime(), nullable=True),
    sa.Column('last_monitoring_change', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('resources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('current_level', sa.Float(), nullable=True),
    sa.Column('capacity', sa.Float(), nullable=True),
    sa.Column('units', sa.String(), nullable=True),
    sa.Column('refill_threshold', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sensors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('additionalInfo', sa.JSON(), nullable=True),
    sa.Column('keys', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('actuator_resources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actuator_id', sa.String(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('relationship_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['actuator_id'], ['actuators.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actuator_sensor',
    sa.Column('actuator_id', sa.String(), nullable=False),
    sa.Column('sensor_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['actuator_id'], ['actuators.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('actuator_id', 'sensor_id')
    )
    op.create_table('irrigation_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Float(), nullable=True),
    sa.Column('water_used', sa.Float(), nullable=True),
    sa.Column('source_tank_id', sa.String(), nullable=True),
    sa.Column('primary_pump_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['primary_pump_id'], ['actuators.id'], ),
    sa.ForeignKeyConstraint(['source_tank_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('actuator_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['actuator_id'], ['actuators.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_events')
    op.drop_table('irrigation_sessions')
    op.drop_table('actuator_sensor')
    op.drop_table('actuator_resources')
    op.drop_table('sensors')
    op.drop_table('resources')
    op.drop_table('actuators')
    # ### end Alembic commands ###
