"""Modified columns in actuator table

Revision ID: 13635553d8e9
Revises: 813b3f08dda4
Create Date: 2025-04-05 15:06:52.330829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '13635553d8e9'
down_revision = '813b3f08dda4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actuator_sensor')
    op.drop_table('actuators')
    op.drop_table('sensors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('unit', sa.VARCHAR(), nullable=True),
    sa.Column('threshold', sa.FLOAT(), nullable=True),
    sa.Column('label', sa.VARCHAR(), nullable=True),
    sa.Column('additionalInfo', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('actuators',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('state', sa.BOOLEAN(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('label', sa.VARCHAR(), nullable=True),
    sa.Column('additionalInfo', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('actuator_sensor',
    sa.Column('actuator_id', sa.VARCHAR(), nullable=False),
    sa.Column('sensor_id', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['actuator_id'], ['actuators.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('actuator_id', 'sensor_id')
    )
    # ### end Alembic commands ###
